json-schema-full-bird.json
json-schema-full-bird_chem_comp.json
json-schema-full-bird_chem_comp_core.json
json-schema-full-chem_comp.json
json-schema-full-chem_comp_core.json
json-schema-full-cluster_members.json
json-schema-full-cluster_provenance.json
json-schema-full-drugbank_core.json
json-schema-full-entity_members.json
json-schema-full-family.json
json-schema-full-ihm_dev.json
json-schema-full-pdbx.json
json-schema-full-pdbx_core_assembly.json
json-schema-full-pdbx_core_entity.json
json-schema-full-pdbx_core_entity_instance.json
json-schema-full-pdbx_core_entity_instance_validation.json
json-schema-full-pdbx_core_entity_monomer.json
json-schema-full-pdbx_core_entry.json
json-schema-full-pdbx_ext.json
json-schema-full-rcsb_data_exchange_status.json
json-schema-full-repository_holdings_current.json
json-schema-full-repository_holdings_insilico_models.json
json-schema-full-repository_holdings_prerelease.json
json-schema-full-repository_holdings_removed.json
json-schema-full-repository_holdings_removed_audit_authors.json
json-schema-full-repository_holdings_superseded.json
json-schema-full-repository_holdings_transferred.json
json-schema-full-repository_holdings_unreleased.json
json-schema-full-repository_holdings_update.json
json-schema-min-bird.json
json-schema-min-bird_chem_comp.json
json-schema-min-bird_chem_comp_core.json
json-schema-min-chem_comp.json
json-schema-min-chem_comp_core.json
json-schema-min-cluster_members.json
json-schema-min-cluster_provenance.json
json-schema-min-drugbank_core.json
json-schema-min-entity_members.json
json-schema-min-family.json
json-schema-min-ihm_dev.json
json-schema-min-pdbx.json
json-schema-min-pdbx_core_assembly.json
json-schema-min-pdbx_core_entity.json
json-schema-min-pdbx_core_entity_instance.json
json-schema-min-pdbx_core_entity_instance_validation.json
json-schema-min-pdbx_core_entity_monomer.json
json-schema-min-pdbx_core_entry.json
json-schema-min-pdbx_ext.json
json-schema-min-rcsb_data_exchange_status.json
json-schema-min-repository_holdings_current.json
json-schema-min-repository_holdings_insilico_models.json
json-schema-min-repository_holdings_prerelease.json
json-schema-min-repository_holdings_removed.json
json-schema-min-repository_holdings_removed_audit_authors.json
json-schema-min-repository_holdings_superseded.json
json-schema-min-repository_holdings_transferred.json
json-schema-min-repository_holdings_unreleased.json
json-schema-min-repository_holdings_update.json
